source 'https://rubygems.org'
ruby '2.1.5'

gem 'bundler'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-router'
gem 'activerecord'
gem 'pg'
gem 'dotenv'
gem 'database_cleaner'
gem 'bcrypt'
